.TH "md__r_e_a_d_m_e" 3 "Ср 28 Июл 2021" "Version 1" "CircleCaptcha" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- CircleCaptcha 
Captcha with random circles
.PP
Капча (CAPTCHA), основанная на подсчёте пересекающихся полупрозрачных кругов\&. Может использоваться с любыми веб-системами\&. Сам генератор рисунков написан на языке Perl и может исполняться на любой платформе\&. 
